//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GradesPublication {
    
    private uint professorIDField;
    
    private string campusField;
    
    private string courseField;
    
    private string classField;
    
    private string evaluationTypeField;
    
    private GradesPublicationStudentEvaluation[] evaluationsField;
    
    /// <remarks/>
    public uint ProfessorID {
        get {
            return this.professorIDField;
        }
        set {
            this.professorIDField = value;
        }
    }
    
    /// <remarks/>
    public string Campus {
        get {
            return this.campusField;
        }
        set {
            this.campusField = value;
        }
    }
    
    /// <remarks/>
    public string Course {
        get {
            return this.courseField;
        }
        set {
            this.courseField = value;
        }
    }
    
    /// <remarks/>
    public string Class {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
    
    /// <remarks/>
    public string EvaluationType {
        get {
            return this.evaluationTypeField;
        }
        set {
            this.evaluationTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("StudentEvaluation", IsNullable=false)]
    public GradesPublicationStudentEvaluation[] Evaluations {
        get {
            return this.evaluationsField;
        }
        set {
            this.evaluationsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GradesPublicationStudentEvaluation {
    
    private uint studentIDField;
        
    private double scoreField;
    
    /// <remarks/>
    public uint StudentID {
        get {
            return this.studentIDField;
        }
        set {
            this.studentIDField = value;
        }
    }
    
    /// <remarks/>
    public double Score {
        get {
            return this.scoreField;
        }
        set {
            this.scoreField = value;
        }
    }
}
