//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace WebSecureGrades.GradesCertificator {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GradesCertifierSoap", Namespace="http://edumaterialcertifcator.net/gradescertifier")]
    public partial class GradesCertifier : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SignGradesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GradesCertifier() {
            this.Url = global::WebSecureGrades.Properties.Settings.Default.WebSecureGrades_GradesCertificator_GradesCertifier;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SignGradesCompletedEventHandler SignGradesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://edumaterialcertifcator.net/gradescertifier/SignGrades", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://edumaterialcertifcator.net/gradescertifier")]
        public string SignGrades([System.Xml.Serialization.XmlElementAttribute(Namespace="http://edumaterialcertifcator.net/gradescertifier", IsNullable=true)] GradesPublication GradesPublication) {
            object[] results = this.Invoke("SignGrades", new object[] {
                        GradesPublication});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SignGradesAsync(GradesPublication GradesPublication) {
            this.SignGradesAsync(GradesPublication, null);
        }
        
        /// <remarks/>
        public void SignGradesAsync(GradesPublication GradesPublication, object userState) {
            if ((this.SignGradesOperationCompleted == null)) {
                this.SignGradesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignGradesOperationCompleted);
            }
            this.InvokeAsync("SignGrades", new object[] {
                        GradesPublication}, this.SignGradesOperationCompleted, userState);
        }
        
        private void OnSignGradesOperationCompleted(object arg) {
            if ((this.SignGradesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignGradesCompleted(this, new SignGradesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edumaterialcertifcator.net/gradescertifier")]
    public partial class GradesPublication {
        
        private int professorIDField;
        
        private string campusField;
        
        private string courseField;
        
        private string classField;
        
        private string evaluationTypeField;
        
        private StudentEvaluation[] evaluationsField;
        
        /// <remarks/>
        public int ProfessorID {
            get {
                return this.professorIDField;
            }
            set {
                this.professorIDField = value;
            }
        }
        
        /// <remarks/>
        public string Campus {
            get {
                return this.campusField;
            }
            set {
                this.campusField = value;
            }
        }
        
        /// <remarks/>
        public string Course {
            get {
                return this.courseField;
            }
            set {
                this.courseField = value;
            }
        }
        
        /// <remarks/>
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        public string EvaluationType {
            get {
                return this.evaluationTypeField;
            }
            set {
                this.evaluationTypeField = value;
            }
        }
        
        /// <remarks/>
        public StudentEvaluation[] Evaluations {
            get {
                return this.evaluationsField;
            }
            set {
                this.evaluationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edumaterialcertifcator.net/gradescertifier")]
    public partial class StudentEvaluation {
        
        private int studentIDField;
        
        private double scoreField;
        
        /// <remarks/>
        public int StudentID {
            get {
                return this.studentIDField;
            }
            set {
                this.studentIDField = value;
            }
        }
        
        /// <remarks/>
        public double Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SignGradesCompletedEventHandler(object sender, SignGradesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignGradesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignGradesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591