//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace WebSecureGrades.GradesPublisher {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GradesPublisherSoap", Namespace="http://edugradespublisher.net/gradespublisher")]
    public partial class GradesPublisher : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Token tokenValueField;
        
        private System.Threading.SendOrPostCallback PublishGradesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GradesPublisher() {
            this.Url = global::WebSecureGrades.Properties.Settings.Default.WebSecureGrades_GradesPublisher_GradesPublisher;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Token TokenValue {
            get {
                return this.tokenValueField;
            }
            set {
                this.tokenValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PublishGradesCompletedEventHandler PublishGradesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TokenValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://edugradespublisher.net/gradespublisher/PublishGrades", RequestNamespace="http://edugradespublisher.net/gradespublisher", ResponseNamespace="http://edugradespublisher.net/gradespublisher", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PublishGrades([System.Xml.Serialization.XmlElementAttribute(Namespace="")] publication publication, string signature) {
            object[] results = this.Invoke("PublishGrades", new object[] {
                        publication,
                        signature});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PublishGradesAsync(publication publication, string signature) {
            this.PublishGradesAsync(publication, signature, null);
        }
        
        /// <remarks/>
        public void PublishGradesAsync(publication publication, string signature, object userState) {
            if ((this.PublishGradesOperationCompleted == null)) {
                this.PublishGradesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPublishGradesOperationCompleted);
            }
            this.InvokeAsync("PublishGrades", new object[] {
                        publication,
                        signature}, this.PublishGradesOperationCompleted, userState);
        }
        
        private void OnPublishGradesOperationCompleted(object arg) {
            if ((this.PublishGradesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PublishGradesCompleted(this, new PublishGradesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://edugradespublisher.net/gradespublisher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://edugradespublisher.net/gradespublisher", IsNullable=false)]
    public partial class Token : System.Web.Services.Protocols.SoapHeader {
        
        private string certificateTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string CertificateToken {
            get {
                return this.certificateTokenField;
            }
            set {
                this.certificateTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class publication {
        
        private uint professorIDField;
        
        private string campusField;
        
        private string courseField;
        
        private string classField;
        
        private string evaluationTypeField;
        
        private ArrayOfGradesPublicationStudentEvaluationStudentEvaluation[] evaluationsField;
        
        /// <remarks/>
        public uint ProfessorID {
            get {
                return this.professorIDField;
            }
            set {
                this.professorIDField = value;
            }
        }
        
        /// <remarks/>
        public string Campus {
            get {
                return this.campusField;
            }
            set {
                this.campusField = value;
            }
        }
        
        /// <remarks/>
        public string Course {
            get {
                return this.courseField;
            }
            set {
                this.courseField = value;
            }
        }
        
        /// <remarks/>
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        public string EvaluationType {
            get {
                return this.evaluationTypeField;
            }
            set {
                this.evaluationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("StudentEvaluation", IsNullable=false)]
        public ArrayOfGradesPublicationStudentEvaluationStudentEvaluation[] Evaluations {
            get {
                return this.evaluationsField;
            }
            set {
                this.evaluationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ArrayOfGradesPublicationStudentEvaluationStudentEvaluation {
        
        private uint studentIDField;
        
        private double scoreField;
        
        /// <remarks/>
        public uint StudentID {
            get {
                return this.studentIDField;
            }
            set {
                this.studentIDField = value;
            }
        }
        
        /// <remarks/>
        public double Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PublishGradesCompletedEventHandler(object sender, PublishGradesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PublishGradesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PublishGradesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591