//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduGradesPublisher.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentScore
    {
        public int PublicationID { get; set; }
        public int StudentID { get; set; }
        public double Score { get; set; }
    
        public virtual Publication Publication { get; set; }
    }
}
